image: node:12.10.0
options:
  max-time: 10

pipelines:
  branches:
    master:
      - step:
          name: Install and Test and Deploy to Heroku
          script:
            - npm i
            - npm run lint
            - npm run test
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
